---
props:
  auto.commit.interval.ms: 1000
  bootstrap.servers: "localhost:9092"
  enable.auto.commit: true
  group.id: test
  key.deserializer: org.apache.kafka.common.serializa-tion.StringDeserializer
  session.timeout.ms: 30000
  value.deserializer: org.apache.kafka.common.serializa-tion.StringDeserializer